version: '3.8'

services:
  postgres:
    build: ./services/postgres
    volumes:
      - ./:/tmp/db
      - postgres:/var/lib/postgresql/data 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=Arsum
      - PGUSER=postgres
    ports:
      - 1620:5432 

  web:
    build: ./services/web
    command: python3 manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 1348:5000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres

        


volumes:
  postgres:  
